# Site settings
title: Anushree's Blog
description: "A minimal blog template, build with Jekyll."
url: "blog.anushree.org"
author:
  name: "Anushree Majumdar"
  email: "hello@jacoporabolini.com"
  url: "anushree.org"

# Build settings
baseurl: /emerald/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
